module.exports = {
  COSMOS_DB_CONNECTION_STRING: 'COSMOS_DB_CONNECTION_STRING',
  COSMOS_DB_RECEIPTS_CONTAINER: 'COSMOS_DB_RECEIPTS_CONTAINER',
  NOTIFICATION_RECEIPT_QUEUE: 'NOTIFICATION_RECEIPT_QUEUE',
  NOTIFY_BEARER_HEADER: 'NOTIFY_BEARER_HEADER'
}
