module.exports = {
  AzureWebJobsStorage: 'AzureWebJobsStorage',
  COSMOS_DB: 'COSMOS_DB',
  COSMOS_DB_RECEIPTS_COLLECTION: 'COSMOS_DB_RECEIPTS_COLLECTION',
  NOTIFY_BEARER_HEADER: 'NOTIFY_BEARER_HEADER',
  NOTIFICATION_RECEIPT_QUEUE: 'NOTIFICATION_RECEIPT_QUEUE'
}
