#!/usr/bin/env sh

# NOTE: Need to be logged in for this to work. Run `az login`.

# Defaults to specific app name and rg.
FUNCTION_APP_NAME=${FUNCTION_APP_NAME:-shunt-gwa-notification-receipt}
RESOURCE_GROUP=${RESOURCE_GROUP:-shunt-gwa}

echo "Updating app-settings for function app '$FUNCTION_APP_NAME' in resource group '$RESOURCE_GROUP' in '${1-production}' slot "
if [ -n "$1" ]; then
  az functionapp config appsettings set --name "$FUNCTION_APP_NAME" --resource-group "$RESOURCE_GROUP" --settings "@app-settings.$1.json" --slot "$1"
else
  az functionapp config appsettings set --name "$FUNCTION_APP_NAME" --resource-group "$RESOURCE_GROUP" --settings "@app-settings.production.json"
fi
